# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WL3hseT8jJ95eTmSXLa5LyUyUjCi4s2N
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/PS_20174392719_1491204439457_log.csv")

print("Shape of the dataset:", df.shape)
df.head()

df.describe()

fraud_rate = df['isFraud'].sum() / len(df)
print(f"Overall Fraud Rate: {fraud_rate:.4f}")
print(f"Interpretation: Approximately {fraud_rate:.2%} of transactions in this dataset are identified as fraudulent.")

# a. Boxplot showing distribution of amount for fraud vs non-fraudulent transactions
plt.figure(figsize=(10, 6))
sns.boxplot(x='isFraud', y='amount', data=df)
plt.yscale('log')
plt.title('Distribution of Transaction Amount for Fraud vs. Non-Fraudulent Transactions (Log Scale)')
plt.xlabel('Is Fraud (0: No, 1: Yes)')
plt.ylabel('Transaction Amount (Log Scale)')
plt.xticks([0, 1], ['Non-Fraudulent', 'Fraudulent'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# b. Bar chart showing fraud percentage by transaction type
fraud_by_type = df.groupby('type')['isFraud'].mean().reset_index()
fraud_by_type['fraud_percentage'] = fraud_by_type['isFraud'] * 100

plt.figure(figsize=(10, 6))
sns.barplot(x='type', y='fraud_percentage', data=fraud_by_type, palette='viridis')
plt.title('Fraud Percentage by Transaction Type')
plt.xlabel('Transaction Type')
plt.ylabel('Fraud Percentage (%)')
plt.ylim(0, fraud_by_type['fraud_percentage'].max() * 1.1) # Add some padding to y-axis
plt.grid(axis='y', linestyle='--', alpha=0.7)

for index, row in fraud_by_type.iterrows():
    plt.text(index, row['fraud_percentage'] + 0.1, f'{row["fraud_percentage"]:.2f}%', color='black', ha="center")

plt.show()



"""### Fintech Analyst Report: Fraud Analysis

**a. Key Insights from Visualizations:**
Fraud is overwhelmingly concentrated in 'TRANSFER' and 'CASH_OUT' transactions, with other types showing negligible rates. Fraudulent transactions consistently involve significantly higher amounts, as shown by the boxplot and histogram, indicating fraudsters target high-value movements. The correlation heatmap confirms expected balance relationships but doesn't directly reveal fraud drivers, reinforcing that transaction type and amount are key indicators.

**b. Major Business Risk Identified:**
The primary risk is the targeted, high-value nature of fraud within 'TRANSFER' and 'CASH_OUT' transactions. This exposes the institution to substantial financial losses and significant reputational damage. It points to critical vulnerabilities in the existing security and monitoring systems for these specific high-liquidity operations, potentially leading to customer churn and increased regulatory scrutiny.

**c. Actionable Recommendations to Management:**
1.  **Strengthen Real-time Monitoring for Transfers & Cash-Outs:** Implement advanced ML models specifically for these types to detect and intercept high-value fraudulent transactions proactively.
2.  **Adaptive MFA & Dynamic Limits:** Introduce multi-factor authentication and flexible transaction limits for high-risk 'TRANSFER' and 'CASH_OUT' activities, especially for new beneficiaries or unusual amounts.
3.  **Security Protocol Audit:** Conduct a comprehensive audit and re-engineer processes for 'TRANSFER' and 'CASH_OUT' to eliminate systemic vulnerabilities and enhance overall security resilience.


"""